#ifndef TIMER_INTERFACE_H
#define TIMER_INTERFACE_H


enum{

	TIMER0_OV_INT,  /* overflow source */
	TIMER0_OC_INT,   /* Output Compare Match */
	TIMER1_OV_INT,
	TIMER1_OC1A_INT,
	TIMER1_OC1B_INT,
	TIMER1_ICU_INT,
	TIMER2_OV_INT,
	TIMER2_OC_INT,

}typedef TIMER_IntSource_t;

enum{
	TIMER_NO_CLOCK,
	TIMER_NO_PRESCALER,
	TIMER_PRESCALER_DIVISION_8,
	TIMER_PRESCALER_DIVISION_64,
	TIMER_PRESCALER_DIVISION_256,
	TIMER_PRESCALER_DIVISION_1024,
	TIMER_EXTERNAL_CLOCK_FALLING_EDGE,
	TIMER_EXTERNAL_CLOCK_RISING_EDGE,

}typedef TIMER_Prescaler_t;


/*TIMER0*/


enum{
	T0_NORMAL,
	T0_COMPARE_MATCH,
	T0_FAST_PWM,
	T0_PHASE_CORRECT_PWM,

}typedef TIMER0_WFG_Mode_t;

enum{
	T0_INT_OVERFLOW,
	T0_INT_COMPARE,
	T0_INT_DISABLED
}typedef TIMER0_INT_State;

enum{
	T0_OC0_DISCONNECT,
	T0_OC0_NON_PWM_TOGGEL,
	T0_OC0_NON_PWM_CLEAR,
	T0_OC0_NON_PWM_SET,
	T0_OC0_FAST_PWM_CLRON_COM_SETON_TOP,
	T0_OC0_FAST_PWM_SETON_COM_CLRON_TOP,
	T0_OC0_PHASE_CORRECT_PWM_CLRON_UPCOUNTCOM_SETON_DOWNCOUNTCOM,
	T0_OC0_PHASE_CORRECT_PWM_SETON_UPCOUNTCOM_CLRON_DOWNCOUNTCOM
}typedef TIMER0_OUT_HW_Option;

struct{

	TIMER0_WFG_Mode_t  WFG_Mode;
	TIMER_Prescaler_t  Prescaler;
	TIMER0_OUT_HW_Option   Out_HW_Opt;
	TIMER0_INT_State    INT_State;

}typedef TIMER0_cfg_t;


/******************* Timer 1 **********************/
enum{
	TIMER1_OC1A,
	TIMER1_OC1B,
	TIMER1_BOTH
}typedef TIMER1_OUT_PIN;


enum{
	T1_NORMAL,
	T1_PWM_PHASE_CORRECT_8BIT,
	T1_PWM_PHASE_CORRECT_9BIT,
	T1_PWM_PHASE_CORRECT_10BIT,
	T1_CTC_TOP_OCRA1,
	T1_FAST_PWM_8BIT,
	T1_FAST_PWM_9BIT,
	T1_FAST_PWM_10BIT,
	T1_PWM_PHASE_FREQENCY_CORRECT_TOP_ICR1,
	T1_PWM_PHASE_FREQENCY_CORRECT_TOP_OCR1A,
	T1_PWM_PHASE_CORRECT_TOP_ICR1,
	T1_PWM_PHASE_CORRECT_TOP_OCR1A,
	T1_CTC_TOP_ICR1,
	T1_FAST_PWM_TOP_ICR1,
	T1_FAST_PWM_TOP_OCR1A,
}typedef TIMER1_WFG_Mode_t;


enum{
	T1_OC1A_DISCONNECT,
	T1_OC1A_NON_PWM_TOGGEL_ONCOMPARE,
	T1_OC1A_NON_PWM_CLEAR_ONCOMPARE,
	T1_OC1A_NON_PWM_SET_ONCOMPARE,
	T1_OC1A_FAST_PWM_CLRON_COM_SETON_TOP,
	T1_OC1A_FAST_PWM_SETON_COM_CLRON_TOP,
	T1_OC1A_PHASE_CORRECT_PWM_CLRON_UPCOUNTCOM_SETON_DOWNCOUNTCOM,
	T1_OC1A_PHASE_CORRECT_PWM_SETON_UPCOUNTCOM_CLRON_DOWNCOUNTCOM
}typedef TIMER1_OC1A_OutPin_State;

enum{
	T1_OC1B_DISCONNECT,
	T1_OC1B_NON_PWM_TOGGEL_ONCOMPARE,
	T1_OC1B_NON_PWM_CLEAR_ONCOMPARE,
	T1_OC1B_NON_PWM_SET_ONCOMPARE,
	T1_OC1B_FAST_PWM_CLRON_COM_SETON_TOP,
	T1_OC1B_FAST_PWM_SETON_COM_CLRON_TOP,
	T1_OC1B_PHASE_CORRECT_PWM_CLRON_UPCOUNTCOM_SETON_DOWNCOUNTCOM,
	T1_OC1B_PHASE_CORRECT_PWM_SETON_UPCOUNTCOM_CLRON_DOWNCOUNTCOM
}typedef TIMER1_OC1B_OutPin_State;
enum{
	T1_INT_ICU,
	T1_INT_COMPARE_OCIE1A,
	T1_INT_COMPARE_OCIE1B,
	T1_INT_COMPARE_OCIE1A_B,
	T1_INT_OVERFLOW,
	T1_INT_DISABLED
}typedef TIMER1_INT_State;

enum{
	T1_ICU_FALLING_EDGE,
	T1_ICU_RISING_EDGE,
	T1_ICU_NONE
}typedef TIMER1_ICU_Edge_Opt;

enum{
	T1_ICU_ENABLED_NOISE_CANCELER,
	T1_ICU_DISABLED_NOISE_CANCELER
}typedef TIMER1_ICU_Noise_Cancle_State;

enum{
	T1_OCR1A_TOP,
	T1_ICR1_TOP
}typedef TIMER1_Top_Opt;
struct{

	TIMER1_WFG_Mode_t  WFG_Mode;
	TIMER1_OC1A_OutPin_State  OC1A_Opt;
	TIMER1_OC1B_OutPin_State  OC1B_Opt;
	TIMER_Prescaler_t  Prescaler;
	TIMER1_ICU_Edge_Opt    ICU_Trigger_Opt;
	TIMER1_ICU_Noise_Cancle_State  ICU_Noise_State;
	TIMER1_INT_State    INT_State;

}typedef TIMER1_cfg_t;

/******************** Timer/Counter 2 *************************/

enum{
	TIMER2_NO_CLOCK,
	TIMER2_NO_PRESCALER,
	TIMER2_PRESCALER_DIVISION_8,
	TIMER2_PRESCALER_DIVISION_32,
	TIMER2_PRESCALER_DIVISION_64,
	TIMER2_PRESCALER_DIVISION_128,
	TIMER2_PRESCALER_DIVISION_256,
	TIMER2_PRESCALER_DIVISION_1024,

}typedef TIMER2_Prescaler_t;




enum{
	T2_NORMAL,
	T2_COMPARE_MATCH,
	T2_FAST_PWM,
	T2_PHASE_CORRECT_PWM,

}typedef TIMER2_WFG_Mode_t;

enum{
	T2_INT_OVERFLOW,
	T2_INT_COMPARE,
	T2_INT_DISABLED
}typedef TIMER2_INT_State;

enum{
	T2_OC2_DISCONNECT,
	T2_OC2_NON_PWM_TOGGEL,
	T2_OC2_NON_PWM_CLEAR,
	T2_OC2_NON_PWM_SET,
	T2_OC2_FAST_PWM_CLRON_COM_SETON_TOP,
	T2_OC2_FAST_PWM_SETON_COM_CLRON_TOP,
	T2_OC2_PHASE_CORRECT_PWM_CLRON_UPCOUNTCOM_SETON_DOWNCOUNTCOM,
	T2_OC2_PHASE_CORRECT_PWM_SETON_UPCOUNTCOM_CLRON_DOWNCOUNTCOM
}typedef TIMER2_OUT_HW_Option;

enum{
	T2_IO_CLOCK,
	T2_EXTERNAL_CLOCK,
}typedef TIMER2_Clock_Source;

struct{

	TIMER2_WFG_Mode_t  WFG_Mode;
	TIMER2_Clock_Source   Clock_opt;
	TIMER2_Prescaler_t  Prescaler;
	TIMER2_OUT_HW_Option   Out_HW_Opt;
	TIMER2_INT_State    INT_State;

}typedef TIMER2_cfg_t;












/*************************************************************/
uint8 TIMER0_u8Init(const TIMER0_cfg_t  *Copy_suCfg);
uint8 TIMER1_u8Init(const TIMER1_cfg_t  *Copy_suCfg);
uint8 TIMER2_u8Init(const TIMER2_cfg_t  *Copy_suCfg);
uint8 TIMER_u8SetCallBackFunc(uint8 Copy_u8IntSource,void(*Copy_pvCallBackFucn)(void));


void TIMER0_voidSetPreloadValue(uint8 Copy_u8PreloadVal);
void TIMER0_voidSetCompareValue(uint8 Copy_u8CompareVal);
void TIMER0_voidSetPrescaler(TIMER_Prescaler_t  Copy_PrescalerVal);
uint8 TIMER0_u8SetCompareOutputMode(TIMER0_OUT_HW_Option Copy_u8OutputMode);
uint8  TIMER0_u8EnableInt(TIMER0_INT_State Copy_sIntOpt);
uint8  TIMER0_u8DisableInt(TIMER0_INT_State Copy_sIntOpt);
void  TIMER0_vStopTimer();


/*Out Pin TIMER1_OC1A,  TIMER1_OC1B*/
uint8 TIMER1_u8SetCompareValue(TIMER1_OUT_PIN Copy_OutPin,uint16 Copy_u16CompareVal);
uint8 TIMER1_u8SetTopValue(TIMER1_Top_Opt Copy_u8TopOpt, uint16 Copy_u16TopValue);
void TIMER1_voidSetTimerValue(uint16 Copy_u8TimerVal);
uint16 TIMER1_u16ReadTimerVal(void);
void TIMER1_voidSetPrescaler(TIMER_Prescaler_t  Copy_PrescalerVal);
uint8 TIMER1_u8Set_OC1A_OutPinState(TIMER1_OC1A_OutPin_State Copy_u8OC1A_Opt);
uint8 TIMER1_u8Set_OC1B_OutPinState(TIMER1_OC1B_OutPin_State Copy_u8OC1B_Opt);
uint8 TIMER1_u8Set_ICU_Edge_Trigger(TIMER1_ICU_Edge_Opt  Copy_u8ICU_Trigger_Opt);
uint16 TIMER1_u16ReadTimerTopICR1(void);
uint8  TIMER1_u8EnableInt(TIMER1_INT_State Copy_sIntOpt);
uint8  TIMER1_u8DisableInt(TIMER1_INT_State Copy_sIntOpt);
void  TIMER1_vStopTimer();

/*Timer/Counter 2*/

void TIMER2_voidSetPreloadValue(uint8 Copy_u8PreloadVal);
void TIMER2_voidSetCompareValue(uint8 Copy_u8CompareVal);
void TIMER2_voidSetPrescaler(TIMER2_Prescaler_t  Copy_PrescalerVal);
uint8 TIMER2_u8SetCompareOutputMode(TIMER2_OUT_HW_Option Copy_u8OutputMode);
uint8  TIMER2_u8EnableInt(TIMER2_INT_State Copy_sIntOpt);
uint8  TIMER2_u8DisableInt(TIMER2_INT_State Copy_sIntOpt);
void  TIMER2_vStopTimer();



#endif
